### ISSUE TITLE
A question about `gometh`

### ISSUE THREAD

**Issue by QianhuiWan** [Oshlack/missMethyl#1]
Hi Oshlack, I updated `missMethyl` package last week, and when I rerun my analysis I found my results from`gometh` and `gsameth` all changed. Do you know why this happen? Do I need to change back to the old version? Thank you so much. My codes are as follows:

```
c2_reactome<-read.gmt("/home/qianhui/DNAme/data/GSEA_MsigDB/c2.cp.reactome.v6.2.entrez.gmt") 

c2_reactomeList <- split(c2_reactome$gene, c2_reactome$ont) 

gsaMeth_DMRprobesReactome <- gsameth(sig.cpg = ProbesInDMRs.names, all.cpg = allProbesInDMRs.names, collection = c2_reactomeList, array.type = "EPIC", prior.prob = TRUE, ann=ann850k)

gsaMeth_DMRprobesReactome[gsaMeth_DMRprobesReactome[,4]<0.05,] 

topGSA(gsaMeth_DMRprobesReactome, number = 10)
```

**Comment by JovMaksimovic** [comment]
Hi,
I have updated missMethyl to now use the newest Illumina annotation (IlluminaHumanMethylationEPICanno.ilm10b4.hg19) by default. You can either revert to using the Bioconductor release version of missMethyl, which still uses the older annotation, or you can pass the older annotation to the gometh function directly:
```{r}
# load older version of the Illumina annotation 
library(IlluminaHumanMethylation450kanno.ilmn12.hg19)
# get older version of the annotation
ann <- getAnnotation(IlluminaHumanMethylation450kanno.ilmn12.hg19)
# pass old annotation to gometh using the "anno" parameter.
gst <- gometh(sig.cpg = sigcpgs, all.cpg = allcpgs, collection = "GO", prior.prob = TRUE, anno = ann)
```

**Comment by QianhuiWan** [comment]
Thank you so much!
