### ISSUE TITLE
support other assay type?

### ISSUE THREAD

**Issue by wbvguo** [Oshlack/missMethyl#12]
Hi,

may I ask if this tool can be extended to support other data types beyond the methylation array (for example the WGBS data, RRBS data, etc)?

Thanks

**Comment by JovMaksimovic** [comment]
Hi,
We have been thinking about doing that for a while, but it's a significant time commitment as the sequencing data will have very different characteristics and biases than the array data. These will need to be investigated and appropriate analysis algorithms developed and tested. It's probably enough work for at least part of PhD project, if we can find a student to work on it.

**Comment by wbvguo** [comment]
Thanks for your replies, may I ask if you, by any chance, know any gene set enrichment analysis tool that accepts a user-specified background gene list? For example, if the technology is only able to capture a list of genes,  after differential analysis, we want to know what pathway is enriched in the differential gene sets, is there an enrichment method that can use these captured genes (instead of using all the genes) as background when conducting the enrichment analysis?
