### ISSUE TITLE
gometh fails for "KEGG" because .getKEGG uses wrong URL

### ISSUE THREAD

**Issue by snowpong** [Oshlack/missMethyl#13]
For gometh with "KEGG" you call your internal function .getKEGG() which fails.

To reproduce simply call: `missMethyl:::.getKEGG()` Which produces:
```
Error in file(file, "rt") : 
  cannot open the connection to 'http://rest.kegg.jp/list/pathway/Hsa'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'https://rest.kegg.jp/list/pathway/Hsa': HTTP status was '400 Bad Request'
```

The fix is to change your "Hsa" to "hsa" in .getKEGG [at this line](https://github.com/Oshlack/missMethyl/blob/20dc68d2db5a9860b1947b1034538ca408f6d66e/R/gometh.R#L269).
To test, compare [https://rest.kegg.jp/list/pathway/hsa](https://rest.kegg.jp/list/pathway/hsa) (works) [https://rest.kegg.jp/list/pathway/Hsa](https://rest.kegg.jp/list/pathway/Hsa) (fails with HTTP ERROR 400)

_Update:_ I've been looking some more into this, and updating from "Hsa" to "hsa" in .getKEGG is not enough - you also have to prepend "path:" to `PathID.PathName$PathwayID` so the merge in [this line](https://github.com/Oshlack/missMethyl/blob/20dc68d2db5a9860b1947b1034538ca408f6d66e/R/gometh.R#L271) succeeds. Then gometh starts working again for "KEGG".

I believe this has started failing because https://www.kegg.jp/kegg/rest/keggapi.html has changed - at least their webpage says: _Last updated: March 1, 2023_. Also https://www.kegg.jp/kegg/rest/ posted on February 20, 2023: _"Announcement: Minor update of KEGG API. Starting on March 1, 2023 the list operation of KEGG API returns KEGG identifiers without the database name in most cases, in compatible with the form shown in Figure 1 of the recent [NAR article](https://doi.org/10.1093/nar/gkac963)."_

**Comment by lopsasnick** [comment]
Thanks for the update! I was trying to run KEGG and was getting this error. I am not great at R, so I was wondering how do you fix the internal code with the line you updated in order to successfully run gometh? Thanks in advance for your help.

**Comment by snowpong** [comment]
Hi @lopsasnick,

I made my own modified `missMethyl:::.getKEGG()` like this:

```
fixed_missMethyl_get_kegg <- function() {
  GeneID.PathID <- limma::getGeneKEGGLinks(
    species.KEGG = "hsa",
    convert = TRUE
  )
  isna <- rowSums(is.na(GeneID.PathID[, 1:2])) > 0.5
  GeneID.PathID <- GeneID.PathID[!isna, ]
  ID.ID <- paste(GeneID.PathID[, 1], GeneID.PathID[, 2], sep = ".")
  d <- !duplicated(ID.ID)
  GeneID.PathID <- GeneID.PathID[d, ]
  PathID.PathName <- limma::getKEGGPathwayNames(
    species.KEGG = "hsa",
    remove.qualifier = TRUE
  )
  PathID.PathName$PathwayID <- paste0("path:", PathID.PathName$PathwayID)
  GeneID.PathID <- merge(GeneID.PathID, PathID.PathName, by = "PathwayID")
  kegg <- tapply(
    GeneID.PathID$GeneID, GeneID.PathID$PathwayID,
    list
  )
  list(idList = kegg, idTable = PathID.PathName)
}
```

and call `patch_miss_methyl()` which points to my fixed version if needed:

```
patch_miss_methyl <- function() {
  test_kegg <- try(missMethyl:::.getKEGG(), silent = TRUE)
  if (class(test_kegg) == "try-error") {
    unlockBinding(".getKEGG", getNamespace("missMethyl"))
    assign(".getKEGG", fixed_missMethyl_get_kegg, getNamespace("missMethyl"))
  }
}
```

Any call to `gometh()` will now use my fixed version. Hope this helps.

**Comment by bphipson** [comment]
Thanks for bringing this to our attention. We will commit a fix - thanks for the detailed code.

**Comment by skatrinli** [comment]
Still a minor issue left. I think you need to remove # [here](https://github.com/Oshlack/missMethyl/blob/master/R/gometh.R#:~:text=%23PathID.PathName%24PathwayID%20%3C%2D%20paste0(%22path%3A%22%2C%20PathID.PathName%24PathwayID)) to make this line (line 271) run.

**Comment by bphipson** [comment]
Can you please try re-installing limma from Bioconductor devel and try again? Gordon Smyth committed a fix to limma as well so that line is no longer necessary when I ran my tests.

**Comment by bphipson** [comment]
I believe the bug has been fixed in Bioconductor release and devel so please give it a try and see if it works.

**Comment by skatrinli** [comment]
It works now! The line is no longer needed. Thanks!

--

Seyma Katrinli, PhD
Pronunciation: shay-mah kaat-rin-lih (hear on Namedrop<https://namedrop.io/seymakatrinli>)

Instructor
Gynecology and Obstetrics
Emory University School of Medicine
101 Woodruff Circle NE, Ste 2205A
Atlanta, GA 30322




From: bphipson ***@***.***>
Date: Wednesday, March 22, 2023 at 7:14 PM
To: Oshlack/missMethyl ***@***.***>
Cc: Katrinli, Seyma ***@***.***>, Comment ***@***.***>
Subject: [External] Re: [Oshlack/missMethyl] gometh fails for "KEGG" because .getKEGG uses wrong URL (Issue #13)

I believe the bug has been fixed in Bioconductor release and devel so please give it a try and see if it works.

**Comment by snowpong** [comment]
The limma change is here https://code.bioconductor.org/browse/limma/commit/6641c256c83f36822e207cca94f64075a49704e3
