### ISSUE TITLE
Calling gometh(sig.cpg, collection = 'KEGG') results in error, cannot open URL

### ISSUE THREAD

**Issue by s-basrai** [Oshlack/missMethyl#18]
Hello,

I'm running into the following problem when trying to call gometh for KEGG pathway enrichment:

```
> kegg.result = gometh(sig.cpg = sms, collection = 'KEGG')
All input CpGs are used for testing.
Error in file(file, "rt") : 
  cannot open the connection to 'http://rest.kegg.jp/list/pathway/Hsa'
In addition: Warning message:
In file(file, "rt") :
  cannot open URL 'https://rest.kegg.jp/list/pathway/Hsa': HTTP status was '400 Bad Request'
```

Trying to paste the URL into my browser does indeed lead to an HTTP 400 error. The URL works when "Hsa" is instead "hsa". Do you know how I can fix this/change the URL gometh tries to connect to?

Thanks,
SB

**Comment by bphipson** [comment]
We have fixed this bug, please reinstall the limma and missMethyl packages.

Thanks!
